apiVersion: v1
kind: PersistentVolume
metadata: 
  name: "statefulset-pgdata"
  labels:
    name: "statefulset-pgdata"
spec: 
#  storageClassName: manual
  capacity: 
    storage: "5Gi"
  accessModes: ["ReadWriteMany"]
  hostPath: 
    path: "/var/root/docker/postgres/k8s-script/ha-postgresql/test2/pgdata-0"
  persistentVolumeReclaimPolicy: Retain
